<a href="https://colab.research.google.com/github/Advait019/G-Collab/blob/main/Pandas_Advanced_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [1]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [2]:
# a =
a= pd.Series([100,200,300,400])

Print a, and data type

In [3]:

print(a)
print(type(a))

0    100
1    200
2    300
3    400
dtype: int64
<class 'pandas.core.series.Series'>

Using indexing access the element 300 from the series a.

In [4]:
a[2]

np.int64(300)

What are the values of index for series a?

In [5]:
a.index

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [6]:
a.index=['c','a','b','d']

Access the value in the series with index 'd'

In [7]:


a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [8]:
a.sort_index()

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [9]:
# b =

b=pd.Series([800,450,100],index=['e','f','g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [10]:
# a =
a= pd.concat([a,b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

In [11]:
#print a again after appending b into it
a

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [12]:
# a =
a.sort_values(ascending=False)

e    800
f    450
d    400
b    300
a    200
c    100
g    100
dtype: int64

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [13]:
# df =


df=pd.DataFrame(a)
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  450
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [14]:

df.shape

#// It implies that there are 7 rows and 1 column

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [15]:
# yep its same as the series.
df.index

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [16]:
print('The head of the dataframe',df.head())
print('The tail of the dataframe', df.tail())
#// Head of the dataframe represents the first 5 values of the dataframe, where as Tail of the dataframe represent the last 5 values.

The head of the dataframe      0
c  100
a  200
b  300
d  400
e  800
The tail of the dataframe      0
b  300
d  400
e  800
f  450
g  100

Rename the column of the dataframe as 'points'

In [17]:

df.columns=['points']
df

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [18]:
#Create fruits array

# fruits =

fruits=np.random.choice(['orange','mango','apple'],7)
print(fruits)

['apple' 'orange' 'mango' 'apple' 'apple' 'mango' 'apple']

In [19]:
#Create series fruits out of fruits array

# fruits =
fruits=pd.Series(fruits)
print(fruits)

0     apple
1    orange
2     mango
3     apple
4     apple
5     mango
6     apple
dtype: object

Change the index of fruits to the index of dataframe df

In [20]:
fruits.index=df.index
print(fruits)

c     apple
a    orange
b     mango
d     apple
e     apple
f     mango
g     apple
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [21]:
df['fruits']= fruits
df.head()

   points  fruits
c     100   apple
a     200  orange
b     300   mango
d     400   apple
e     800   apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [22]:
# d1 =

d1=pd.DataFrame({'City':['Chandigarh','Delhi','Kanpur','Chennai','Manali'],'Temperature':[15,22,20,26,-2]})

Print(d1)

In [23]:

d1

         City  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [24]:
d1.shape

(5, 2)

Set city = d1['city']

In [25]:
Set_city=d1['City']
print(Set_city)

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: City, dtype: object

print city <br>
What is the type of city.

In [26]:
set_city=d1['City']
print(set_city)
print(type(set_city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: City, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [27]:
# d2 =

d2=pd.DataFrame({'City':['Bengalaru','Coimbatore','Srirangam','Pondicherry'],'Temperature':[24,35,36,39]})

print the shape of this dataframe

In [28]:
d2.shape

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [29]:
# d3 =

d3=pd.concat([d1,d2])
print(d3)

          City  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [30]:
# City where temperature is less than 20
d3_filtered = d3[d3["Temperature"] <= 20]
d3_filtered

         City  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [31]:
# City where temperature is greater than 35
d3_filtered1 = d3[d3["Temperature"] >= 35]
d3_filtered1

          City  Temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [32]:
# write function here
def is_ut(x):
 if x in ['Chandigarh','Pondicherry','Delhi']:
  return True
 else:
  return False
#     # write code below

d3['is_ut'] = d3['City'].apply(is_ut)
d3

          City  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

In [33]:
# print d3

d3

          City  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
0    Bengalaru           24  False
1   Coimbatore           35  False
2    Srirangam           36  False
3  Pondicherry           39   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [34]:
# write function here
def c_to_f(x):
  return (x*9/5)+32

c_to_f(10)

d3['Ferenhiet']=d3['Temperature'].apply(c_to_f)
d3['Ferenhiet']

0     59.0
1     71.6
2     68.0
3     78.8
4     28.4
0     75.2
1     95.0
2     96.8
3    102.2
Name: Ferenhiet, dtype: float64

In [35]:
# check function c_to_f(10)

c_to_f(10)

50.0

In [36]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temp_ferenhiet']=d3['Temperature'].apply(c_to_f)
d3['temp_ferenhiet']

0     59.0
1     71.6
2     68.0
3     78.8
4     28.4
0     75.2
1     95.0
2     96.8
3    102.2
Name: temp_ferenhiet, dtype: float64

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [37]:
d3[d3['is_ut']==True]

          City  Temperature  is_ut  Ferenhiet  temp_ferenhiet
0   Chandigarh           15   True       59.0            59.0
1        Delhi           22   True       71.6            71.6
3  Pondicherry           39   True      102.2           102.2

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [38]:
d3[d3['temp_ferenhiet']>90]

          City  Temperature  is_ut  Ferenhiet  temp_ferenhiet
1   Coimbatore           35  False       95.0            95.0
2    Srirangam           36  False       96.8            96.8
3  Pondicherry           39   True      102.2           102.2

Select only the first three rows of the dataframe d1.

In [39]:
d3.head(3)

         City  Temperature  is_ut  Ferenhiet  temp_ferenhiet
0  Chandigarh           15   True       59.0            59.0
1       Delhi           22   True       71.6            71.6
2      Kanpur           20  False       68.0            68.0

Select all the rows and last two columns in the dataframe.

In [40]:
d3.iloc[:,[-2,-1]]

   Ferenhiet  temp_ferenhiet
0       59.0            59.0
1       71.6            71.6
2       68.0            68.0
3       78.8            78.8
4       28.4            28.4
0       75.2            75.2
1       95.0            95.0
2       96.8            96.8
3      102.2           102.2

## Groupby

In [41]:
# Create a dataframe using dictionary of your choice

# data =

data=pd.DataFrame({'College':['IIM','IIT','NIT','BITS'],'Exams':['CAT','JEE-ADV','JEE','BITSAT'],'Percentile':[99.9,99,95,90]})
data

  College    Exams  Percentile
0     IIM      CAT        99.9
1     IIT  JEE-ADV        99.0
2     NIT      JEE        95.0
3    BITS   BITSAT        90.0

In [42]:
# Use Groupby of single column with aggregate sum()

data.groupby('College')['Exams'].sum()

College
BITS     BITSAT
IIM         CAT
IIT     JEE-ADV
NIT         JEE
Name: Exams, dtype: object

In [43]:
# Use Groupby of single column with aggregate count()

data.groupby('College')['Exams'].count()

College
BITS    1
IIM     1
IIT     1
NIT     1
Name: Exams, dtype: int64

In [44]:
# Use Groupby of single column with aggregate min() and max()

print(data.groupby('College')['Percentile'].min())
print(data.groupby('College')['Percentile'].max())

College
BITS    90.0
IIM     99.9
IIT     99.0
NIT     95.0
Name: Percentile, dtype: float64
College
BITS    90.0
IIM     99.9
IIT     99.0
NIT     95.0
Name: Percentile, dtype: float64

In [45]:
# Use Groupby of any 2 columns with aggregate mean()

data.groupby(['College','Exams'])['Percentile'].mean()

College  Exams
BITS     BITSAT     90.0
IIM      CAT        99.9
IIT      JEE-ADV    99.0
NIT      JEE        95.0
Name: Percentile, dtype: float64

In [46]:
# Use Groupby of any 2 columns with aggregate min() and max()

data.groupby(['College','Exams'])['Percentile'].min()
data.groupby(['College','Exams'])['Percentile'].max()

College  Exams
BITS     BITSAT     90.0
IIM      CAT        99.9
IIT      JEE-ADV    99.0
NIT      JEE        95.0
Name: Percentile, dtype: float64